[package]
name = "output_format"
version = "0.1.0"
edition = "2021"

[dependencies]
amplify = "3.12.0"
serde = "1.0"
serde_yaml = "0.8"
serde_json = "1.0"
clap = { version = "3.1", features = ["derive"] }
colored = "2.0"
